spring:
  batch:
    job:
      enabled: false  # 시작 시 자동 실행 안 함, 스케줄러가 제어

stock:
  price:
    days-back: 1
    scheduler:
      enabled: true
    daily-cron: "0 26 10 * * MON-FRI"

notification:
  scheduler:
    enabled: true
    cron: "0 0 11 * * *"  # 테스트용, 운영 시 제거하면 기본값 0 0 8 * * * 적용
